//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class IMS_KMPORTALEntities : DbContext
    {
        public IMS_KMPORTALEntities()
            : base("name=IMS_KMPORTALEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<IMS_EmployeeDetailList_Result> IMS_EmployeeDetailList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMS_EmployeeDetailList_Result>("IMS_EmployeeDetailList");
        }
    
        public virtual ObjectResult<IMS_EmployeeDetailListByGlobalID_Result> IMS_EmployeeDetailListByGlobalID(string globalid)
        {
            var globalidParameter = globalid != null ?
                new ObjectParameter("globalid", globalid) :
                new ObjectParameter("globalid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMS_EmployeeDetailListByGlobalID_Result>("IMS_EmployeeDetailListByGlobalID", globalidParameter);
        }
    
        public virtual ObjectResult<IMS_EmployeeFullDetailByGlobalID_Result> IMS_EmployeeFullDetailByGlobalID(string globalid)
        {
            var globalidParameter = globalid != null ?
                new ObjectParameter("globalid", globalid) :
                new ObjectParameter("globalid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMS_EmployeeFullDetailByGlobalID_Result>("IMS_EmployeeFullDetailByGlobalID", globalidParameter);
        }
    
        public virtual ObjectResult<IMS_GetHODReportees_Result> IMS_GetHODReportees(string hodglobalid)
        {
            var hodglobalidParameter = hodglobalid != null ?
                new ObjectParameter("hodglobalid", hodglobalid) :
                new ObjectParameter("hodglobalid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMS_GetHODReportees_Result>("IMS_GetHODReportees", hodglobalidParameter);
        }
    
        public virtual ObjectResult<IMS_GetHODS_Result> IMS_GetHODS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMS_GetHODS_Result>("IMS_GetHODS");
        }
    
        public virtual ObjectResult<spChkUserAD_Result> spChkUserAD(string uSER_NAME, string pASSWORD, string authenticationmode, string samAccountName)
        {
            var uSER_NAMEParameter = uSER_NAME != null ?
                new ObjectParameter("USER_NAME", uSER_NAME) :
                new ObjectParameter("USER_NAME", typeof(string));
    
            var pASSWORDParameter = pASSWORD != null ?
                new ObjectParameter("PASSWORD", pASSWORD) :
                new ObjectParameter("PASSWORD", typeof(string));
    
            var authenticationmodeParameter = authenticationmode != null ?
                new ObjectParameter("authenticationmode", authenticationmode) :
                new ObjectParameter("authenticationmode", typeof(string));
    
            var samAccountNameParameter = samAccountName != null ?
                new ObjectParameter("samAccountName", samAccountName) :
                new ObjectParameter("samAccountName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spChkUserAD_Result>("spChkUserAD", uSER_NAMEParameter, pASSWORDParameter, authenticationmodeParameter, samAccountNameParameter);
        }
    
        public virtual ObjectResult<ra_validateemployee_Result> ra_validateemployee(string globalid)
        {
            var globalidParameter = globalid != null ?
                new ObjectParameter("globalid", globalid) :
                new ObjectParameter("globalid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ra_validateemployee_Result>("ra_validateemployee", globalidParameter);
        }
    }
}
