//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class IMSEntities : DbContext
    {
        public IMSEntities()
            : base("name=IMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<checkQRLogin_Result> checkQRLogin(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<checkQRLogin_Result>("checkQRLogin", usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<getAllEmployees_Result> getAllEmployees()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAllEmployees_Result>("getAllEmployees");
        }
    
        public virtual ObjectResult<getCollaborators_Result> getCollaborators(Nullable<int> ideaId)
        {
            var ideaIdParameter = ideaId.HasValue ?
                new ObjectParameter("IdeaId", ideaId) :
                new ObjectParameter("IdeaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getCollaborators_Result>("getCollaborators", ideaIdParameter);
        }
    
        public virtual ObjectResult<getDepartmentDetails_Result> getDepartmentDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getDepartmentDetails_Result>("getDepartmentDetails");
        }
    
        public virtual ObjectResult<getEmployeeByGlobalID_Result> getEmployeeByGlobalID(string globalid)
        {
            var globalidParameter = globalid != null ?
                new ObjectParameter("globalid", globalid) :
                new ObjectParameter("globalid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getEmployeeByGlobalID_Result>("getEmployeeByGlobalID", globalidParameter);
        }
    
        public virtual ObjectResult<getEmployeeByID_Result> getEmployeeByID(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getEmployeeByID_Result>("getEmployeeByID", idParameter);
        }
    
        public virtual ObjectResult<getEmployeesdata_Result> getEmployeesdata()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getEmployeesdata_Result>("getEmployeesdata");
        }
    
        public virtual ObjectResult<geterrorlog_Result> geterrorlog(Nullable<System.DateTime> fromdate, Nullable<System.DateTime> todate, Nullable<int> userid, Nullable<int> locationid, Nullable<int> departmentid)
        {
            var fromdateParameter = fromdate.HasValue ?
                new ObjectParameter("fromdate", fromdate) :
                new ObjectParameter("fromdate", typeof(System.DateTime));
    
            var todateParameter = todate.HasValue ?
                new ObjectParameter("todate", todate) :
                new ObjectParameter("todate", typeof(System.DateTime));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var locationidParameter = locationid.HasValue ?
                new ObjectParameter("locationid", locationid) :
                new ObjectParameter("locationid", typeof(int));
    
            var departmentidParameter = departmentid.HasValue ?
                new ObjectParameter("departmentid", departmentid) :
                new ObjectParameter("departmentid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<geterrorlog_Result>("geterrorlog", fromdateParameter, todateParameter, useridParameter, locationidParameter, departmentidParameter);
        }
    
        public virtual ObjectResult<getLocationDetails_Result> getLocationDetails(Nullable<int> code)
        {
            var codeParameter = code.HasValue ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getLocationDetails_Result>("getLocationDetails", codeParameter);
        }
    
        public virtual ObjectResult<GetLocationDetails_New_Result> GetLocationDetails_New()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLocationDetails_New_Result>("GetLocationDetails_New");
        }
    
        public virtual ObjectResult<getLocationDetailsByCode_Result> getLocationDetailsByCode(Nullable<int> code)
        {
            var codeParameter = code.HasValue ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getLocationDetailsByCode_Result>("getLocationDetailsByCode", codeParameter);
        }
    
        public virtual ObjectResult<getLocationnew_Result> getLocationnew()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getLocationnew_Result>("getLocationnew");
        }
    
        public virtual ObjectResult<getMenuauditLog_Result> getMenuauditLog(Nullable<System.DateTime> fromdate, Nullable<System.DateTime> todate, Nullable<int> userid, Nullable<int> locationid, Nullable<int> departmentid)
        {
            var fromdateParameter = fromdate.HasValue ?
                new ObjectParameter("fromdate", fromdate) :
                new ObjectParameter("fromdate", typeof(System.DateTime));
    
            var todateParameter = todate.HasValue ?
                new ObjectParameter("todate", todate) :
                new ObjectParameter("todate", typeof(System.DateTime));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var locationidParameter = locationid.HasValue ?
                new ObjectParameter("locationid", locationid) :
                new ObjectParameter("locationid", typeof(int));
    
            var departmentidParameter = departmentid.HasValue ?
                new ObjectParameter("departmentid", departmentid) :
                new ObjectParameter("departmentid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getMenuauditLog_Result>("getMenuauditLog", fromdateParameter, todateParameter, useridParameter, locationidParameter, departmentidParameter);
        }
    
        public virtual ObjectResult<getMenulist_Result> getMenulist()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getMenulist_Result>("getMenulist");
        }
    
        public virtual ObjectResult<getpermissionLog_Result> getpermissionLog(Nullable<System.DateTime> fromdate, Nullable<System.DateTime> todate, Nullable<int> userid, Nullable<int> locationid, Nullable<int> departmentid)
        {
            var fromdateParameter = fromdate.HasValue ?
                new ObjectParameter("fromdate", fromdate) :
                new ObjectParameter("fromdate", typeof(System.DateTime));
    
            var todateParameter = todate.HasValue ?
                new ObjectParameter("todate", todate) :
                new ObjectParameter("todate", typeof(System.DateTime));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var locationidParameter = locationid.HasValue ?
                new ObjectParameter("locationid", locationid) :
                new ObjectParameter("locationid", typeof(int));
    
            var departmentidParameter = departmentid.HasValue ?
                new ObjectParameter("departmentid", departmentid) :
                new ObjectParameter("departmentid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getpermissionLog_Result>("getpermissionLog", fromdateParameter, todateParameter, useridParameter, locationidParameter, departmentidParameter);
        }
    
        public virtual ObjectResult<getPermissions_Result> getPermissions()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getPermissions_Result>("getPermissions");
        }
    
        public virtual ObjectResult<getRolelist_Result> getRolelist()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getRolelist_Result>("getRolelist");
        }
    
        public virtual ObjectResult<getRolesauditLog_Result> getRolesauditLog(Nullable<System.DateTime> fromdate, Nullable<System.DateTime> todate, Nullable<int> userid, Nullable<int> locationid, Nullable<int> departmentid)
        {
            var fromdateParameter = fromdate.HasValue ?
                new ObjectParameter("fromdate", fromdate) :
                new ObjectParameter("fromdate", typeof(System.DateTime));
    
            var todateParameter = todate.HasValue ?
                new ObjectParameter("todate", todate) :
                new ObjectParameter("todate", typeof(System.DateTime));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var locationidParameter = locationid.HasValue ?
                new ObjectParameter("locationid", locationid) :
                new ObjectParameter("locationid", typeof(int));
    
            var departmentidParameter = departmentid.HasValue ?
                new ObjectParameter("departmentid", departmentid) :
                new ObjectParameter("departmentid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getRolesauditLog_Result>("getRolesauditLog", fromdateParameter, todateParameter, useridParameter, locationidParameter, departmentidParameter);
        }
    
        public virtual ObjectResult<getRoleWiseMenu_Result> getRoleWiseMenu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getRoleWiseMenu_Result>("getRoleWiseMenu");
        }
    
        public virtual ObjectResult<getRolewisemenuauditLog_Result> getRolewisemenuauditLog(Nullable<System.DateTime> fromdate, Nullable<System.DateTime> todate, Nullable<int> userid, Nullable<int> locationid, Nullable<int> departmentid)
        {
            var fromdateParameter = fromdate.HasValue ?
                new ObjectParameter("fromdate", fromdate) :
                new ObjectParameter("fromdate", typeof(System.DateTime));
    
            var todateParameter = todate.HasValue ?
                new ObjectParameter("todate", todate) :
                new ObjectParameter("todate", typeof(System.DateTime));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var locationidParameter = locationid.HasValue ?
                new ObjectParameter("locationid", locationid) :
                new ObjectParameter("locationid", typeof(int));
    
            var departmentidParameter = departmentid.HasValue ?
                new ObjectParameter("departmentid", departmentid) :
                new ObjectParameter("departmentid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getRolewisemenuauditLog_Result>("getRolewisemenuauditLog", fromdateParameter, todateParameter, useridParameter, locationidParameter, departmentidParameter);
        }
    
        public virtual ObjectResult<getRoleWiseMenuByRoleID_Result> getRoleWiseMenuByRoleID(Nullable<int> roleID)
        {
            var roleIDParameter = roleID.HasValue ?
                new ObjectParameter("RoleID", roleID) :
                new ObjectParameter("RoleID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getRoleWiseMenuByRoleID_Result>("getRoleWiseMenuByRoleID", roleIDParameter);
        }
    
        public virtual ObjectResult<getSettings_Result> getSettings()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getSettings_Result>("getSettings");
        }
    
        public virtual ObjectResult<getsystemlog_Result> getsystemlog(Nullable<System.DateTime> fromdate, Nullable<System.DateTime> todate, Nullable<int> userid, Nullable<int> locationid, Nullable<int> departmentid)
        {
            var fromdateParameter = fromdate.HasValue ?
                new ObjectParameter("fromdate", fromdate) :
                new ObjectParameter("fromdate", typeof(System.DateTime));
    
            var todateParameter = todate.HasValue ?
                new ObjectParameter("todate", todate) :
                new ObjectParameter("todate", typeof(System.DateTime));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var locationidParameter = locationid.HasValue ?
                new ObjectParameter("locationid", locationid) :
                new ObjectParameter("locationid", typeof(int));
    
            var departmentidParameter = departmentid.HasValue ?
                new ObjectParameter("departmentid", departmentid) :
                new ObjectParameter("departmentid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getsystemlog_Result>("getsystemlog", fromdateParameter, todateParameter, useridParameter, locationidParameter, departmentidParameter);
        }
    
        public virtual ObjectResult<gettopcontributers_Result> gettopcontributers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<gettopcontributers_Result>("gettopcontributers");
        }
    
        public virtual ObjectResult<gettopIdeas_Result> gettopIdeas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<gettopIdeas_Result>("gettopIdeas");
        }
    
        public virtual ObjectResult<getusermenu_Result> getusermenu(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getusermenu_Result>("getusermenu", useridParameter);
        }
    
        public virtual ObjectResult<getUserWiseRole_Result> getUserWiseRole()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getUserWiseRole_Result>("getUserWiseRole");
        }
    
        public virtual ObjectResult<getUserWiseRoleById_Result> getUserWiseRoleById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getUserWiseRoleById_Result>("getUserWiseRoleById", idParameter);
        }
    
        public virtual ObjectResult<getUserwiseroleLog_Result> getUserwiseroleLog(Nullable<System.DateTime> fromdate, Nullable<System.DateTime> todate, Nullable<int> userid, Nullable<int> locationid, Nullable<int> departmentid)
        {
            var fromdateParameter = fromdate.HasValue ?
                new ObjectParameter("fromdate", fromdate) :
                new ObjectParameter("fromdate", typeof(System.DateTime));
    
            var todateParameter = todate.HasValue ?
                new ObjectParameter("todate", todate) :
                new ObjectParameter("todate", typeof(System.DateTime));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var locationidParameter = locationid.HasValue ?
                new ObjectParameter("locationid", locationid) :
                new ObjectParameter("locationid", typeof(int));
    
            var departmentidParameter = departmentid.HasValue ?
                new ObjectParameter("departmentid", departmentid) :
                new ObjectParameter("departmentid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getUserwiseroleLog_Result>("getUserwiseroleLog", fromdateParameter, todateParameter, useridParameter, locationidParameter, departmentidParameter);
        }
    
        public virtual ObjectResult<getUWRByID_Result> getUWRByID(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getUWRByID_Result>("getUWRByID", idParameter);
        }
    
        public virtual ObjectResult<IMS_Categorydll_Result> IMS_Categorydll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMS_Categorydll_Result>("IMS_Categorydll");
        }
    
        public virtual ObjectResult<IMS_CloseIdeaValue_Result> IMS_CloseIdeaValue(Nullable<int> ideaId, string globalId)
        {
            var ideaIdParameter = ideaId.HasValue ?
                new ObjectParameter("IdeaId", ideaId) :
                new ObjectParameter("IdeaId", typeof(int));
    
            var globalIdParameter = globalId != null ?
                new ObjectParameter("GlobalId", globalId) :
                new ObjectParameter("GlobalId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMS_CloseIdeaValue_Result>("IMS_CloseIdeaValue", ideaIdParameter, globalIdParameter);
        }
    
        public virtual ObjectResult<IMS_DropIdeaatAwarding_Result> IMS_DropIdeaatAwarding(Nullable<int> id, string globalId, string remarks)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var globalIdParameter = globalId != null ?
                new ObjectParameter("GlobalId", globalId) :
                new ObjectParameter("GlobalId", typeof(string));
    
            var remarksParameter = remarks != null ?
                new ObjectParameter("Remarks", remarks) :
                new ObjectParameter("Remarks", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMS_DropIdeaatAwarding_Result>("IMS_DropIdeaatAwarding", idParameter, globalIdParameter, remarksParameter);
        }
    
        public virtual ObjectResult<IMS_DropIdeaAtShortListing_Result> IMS_DropIdeaAtShortListing(Nullable<int> id, string globalId, string remarks)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var globalIdParameter = globalId != null ?
                new ObjectParameter("GlobalId", globalId) :
                new ObjectParameter("GlobalId", typeof(string));
    
            var remarksParameter = remarks != null ?
                new ObjectParameter("Remarks", remarks) :
                new ObjectParameter("Remarks", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMS_DropIdeaAtShortListing_Result>("IMS_DropIdeaAtShortListing", idParameter, globalIdParameter, remarksParameter);
        }
    
        public virtual ObjectResult<IMS_EvalStatusdll_Result> IMS_EvalStatusdll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMS_EvalStatusdll_Result>("IMS_EvalStatusdll");
        }
    
        public virtual int IMS_freezeTeamFormationbyIdeaid(Nullable<int> ideaId, string globalid)
        {
            var ideaIdParameter = ideaId.HasValue ?
                new ObjectParameter("IdeaId", ideaId) :
                new ObjectParameter("IdeaId", typeof(int));
    
            var globalidParameter = globalid != null ?
                new ObjectParameter("globalid", globalid) :
                new ObjectParameter("globalid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("IMS_freezeTeamFormationbyIdeaid", ideaIdParameter, globalidParameter);
        }
    
        public virtual ObjectResult<IMS_GetCCListById_Result> IMS_GetCCListById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMS_GetCCListById_Result>("IMS_GetCCListById", idParameter);
        }
    
        public virtual ObjectResult<IMS_GetEvaluationList_Result> IMS_GetEvaluationList(Nullable<System.DateTime> fromdate, Nullable<System.DateTime> todate, string globalId)
        {
            var fromdateParameter = fromdate.HasValue ?
                new ObjectParameter("fromdate", fromdate) :
                new ObjectParameter("fromdate", typeof(System.DateTime));
    
            var todateParameter = todate.HasValue ?
                new ObjectParameter("todate", todate) :
                new ObjectParameter("todate", typeof(System.DateTime));
    
            var globalIdParameter = globalId != null ?
                new ObjectParameter("GlobalId", globalId) :
                new ObjectParameter("GlobalId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMS_GetEvaluationList_Result>("IMS_GetEvaluationList", fromdateParameter, todateParameter, globalIdParameter);
        }
    
        public virtual ObjectResult<IMS_GetEvaluationList_admin_Result> IMS_GetEvaluationList_admin(Nullable<System.DateTime> fromdate, Nullable<System.DateTime> todate, string globalId)
        {
            var fromdateParameter = fromdate.HasValue ?
                new ObjectParameter("fromdate", fromdate) :
                new ObjectParameter("fromdate", typeof(System.DateTime));
    
            var todateParameter = todate.HasValue ?
                new ObjectParameter("todate", todate) :
                new ObjectParameter("todate", typeof(System.DateTime));
    
            var globalIdParameter = globalId != null ?
                new ObjectParameter("GlobalId", globalId) :
                new ObjectParameter("GlobalId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMS_GetEvaluationList_admin_Result>("IMS_GetEvaluationList_admin", fromdateParameter, todateParameter, globalIdParameter);
        }
    
        public virtual ObjectResult<IMS_GetFile_Result> IMS_GetFile(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMS_GetFile_Result>("IMS_GetFile", idParameter);
        }
    
        public virtual ObjectResult<IMS_GetFileByModule_Result> IMS_GetFileByModule(Nullable<int> id, string module)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var moduleParameter = module != null ?
                new ObjectParameter("module", module) :
                new ObjectParameter("module", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMS_GetFileByModule_Result>("IMS_GetFileByModule", idParameter, moduleParameter);
        }
    
        public virtual ObjectResult<IMS_GetFilesList_Result> IMS_GetFilesList(Nullable<int> ideaId)
        {
            var ideaIdParameter = ideaId.HasValue ?
                new ObjectParameter("IdeaId", ideaId) :
                new ObjectParameter("IdeaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMS_GetFilesList_Result>("IMS_GetFilesList", ideaIdParameter);
        }
    
        public virtual ObjectResult<IMS_GetIdeaEvaluationByIdeaid_Result> IMS_GetIdeaEvaluationByIdeaid(Nullable<int> ideaid)
        {
            var ideaidParameter = ideaid.HasValue ?
                new ObjectParameter("ideaid", ideaid) :
                new ObjectParameter("ideaid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMS_GetIdeaEvaluationByIdeaid_Result>("IMS_GetIdeaEvaluationByIdeaid", ideaidParameter);
        }
    
        public virtual ObjectResult<IMS_GetIdeaListReport_Result> IMS_GetIdeaListReport(Nullable<System.DateTime> fromdate, Nullable<System.DateTime> todate, Nullable<int> locationid, Nullable<int> departmentid, Nullable<int> categoryid, Nullable<int> statuscode)
        {
            var fromdateParameter = fromdate.HasValue ?
                new ObjectParameter("fromdate", fromdate) :
                new ObjectParameter("fromdate", typeof(System.DateTime));
    
            var todateParameter = todate.HasValue ?
                new ObjectParameter("todate", todate) :
                new ObjectParameter("todate", typeof(System.DateTime));
    
            var locationidParameter = locationid.HasValue ?
                new ObjectParameter("locationid", locationid) :
                new ObjectParameter("locationid", typeof(int));
    
            var departmentidParameter = departmentid.HasValue ?
                new ObjectParameter("departmentid", departmentid) :
                new ObjectParameter("departmentid", typeof(int));
    
            var categoryidParameter = categoryid.HasValue ?
                new ObjectParameter("categoryid", categoryid) :
                new ObjectParameter("categoryid", typeof(int));
    
            var statuscodeParameter = statuscode.HasValue ?
                new ObjectParameter("statuscode", statuscode) :
                new ObjectParameter("statuscode", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMS_GetIdeaListReport_Result>("IMS_GetIdeaListReport", fromdateParameter, todateParameter, locationidParameter, departmentidParameter, categoryidParameter, statuscodeParameter);
        }
    
        public virtual ObjectResult<IMS_GetIdeaListReport_v1_Result> IMS_GetIdeaListReport_v1(Nullable<System.DateTime> fromdate, Nullable<System.DateTime> todate, Nullable<int> locationid, Nullable<int> departmentid, Nullable<int> categoryid, Nullable<int> statuscode)
        {
            var fromdateParameter = fromdate.HasValue ?
                new ObjectParameter("fromdate", fromdate) :
                new ObjectParameter("fromdate", typeof(System.DateTime));
    
            var todateParameter = todate.HasValue ?
                new ObjectParameter("todate", todate) :
                new ObjectParameter("todate", typeof(System.DateTime));
    
            var locationidParameter = locationid.HasValue ?
                new ObjectParameter("locationid", locationid) :
                new ObjectParameter("locationid", typeof(int));
    
            var departmentidParameter = departmentid.HasValue ?
                new ObjectParameter("departmentid", departmentid) :
                new ObjectParameter("departmentid", typeof(int));
    
            var categoryidParameter = categoryid.HasValue ?
                new ObjectParameter("categoryid", categoryid) :
                new ObjectParameter("categoryid", typeof(int));
    
            var statuscodeParameter = statuscode.HasValue ?
                new ObjectParameter("statuscode", statuscode) :
                new ObjectParameter("statuscode", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMS_GetIdeaListReport_v1_Result>("IMS_GetIdeaListReport_v1", fromdateParameter, todateParameter, locationidParameter, departmentidParameter, categoryidParameter, statuscodeParameter);
        }
    
        public virtual ObjectResult<IMS_GetIdeaScroreList_Result> IMS_GetIdeaScroreList(Nullable<System.DateTime> fromdate, Nullable<System.DateTime> todate, string globalId)
        {
            var fromdateParameter = fromdate.HasValue ?
                new ObjectParameter("fromdate", fromdate) :
                new ObjectParameter("fromdate", typeof(System.DateTime));
    
            var todateParameter = todate.HasValue ?
                new ObjectParameter("todate", todate) :
                new ObjectParameter("todate", typeof(System.DateTime));
    
            var globalIdParameter = globalId != null ?
                new ObjectParameter("GlobalId", globalId) :
                new ObjectParameter("GlobalId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMS_GetIdeaScroreList_Result>("IMS_GetIdeaScroreList", fromdateParameter, todateParameter, globalIdParameter);
        }
    
        public virtual ObjectResult<IMS_GetIdeaScroreList_admin_Result> IMS_GetIdeaScroreList_admin(Nullable<System.DateTime> fromdate, Nullable<System.DateTime> todate, string globalId)
        {
            var fromdateParameter = fromdate.HasValue ?
                new ObjectParameter("fromdate", fromdate) :
                new ObjectParameter("fromdate", typeof(System.DateTime));
    
            var todateParameter = todate.HasValue ?
                new ObjectParameter("todate", todate) :
                new ObjectParameter("todate", typeof(System.DateTime));
    
            var globalIdParameter = globalId != null ?
                new ObjectParameter("GlobalId", globalId) :
                new ObjectParameter("GlobalId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMS_GetIdeaScroreList_admin_Result>("IMS_GetIdeaScroreList_admin", fromdateParameter, todateParameter, globalIdParameter);
        }
    
        public virtual ObjectResult<IMS_GetIdeaShortingList_Result> IMS_GetIdeaShortingList(Nullable<System.DateTime> fromdate, Nullable<System.DateTime> todate)
        {
            var fromdateParameter = fromdate.HasValue ?
                new ObjectParameter("fromdate", fromdate) :
                new ObjectParameter("fromdate", typeof(System.DateTime));
    
            var todateParameter = todate.HasValue ?
                new ObjectParameter("todate", todate) :
                new ObjectParameter("todate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMS_GetIdeaShortingList_Result>("IMS_GetIdeaShortingList", fromdateParameter, todateParameter);
        }
    
        public virtual ObjectResult<IMS_GetIdeaTrackingByIdeaid_Result> IMS_GetIdeaTrackingByIdeaid(Nullable<int> ideaid)
        {
            var ideaidParameter = ideaid.HasValue ?
                new ObjectParameter("ideaid", ideaid) :
                new ObjectParameter("ideaid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMS_GetIdeaTrackingByIdeaid_Result>("IMS_GetIdeaTrackingByIdeaid", ideaidParameter);
        }
    
        public virtual ObjectResult<IMS_GetIdeaValues_Result> IMS_GetIdeaValues(Nullable<int> ideaId)
        {
            var ideaIdParameter = ideaId.HasValue ?
                new ObjectParameter("IdeaId", ideaId) :
                new ObjectParameter("IdeaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMS_GetIdeaValues_Result>("IMS_GetIdeaValues", ideaIdParameter);
        }
    
        public virtual ObjectResult<IMS_GetIMSEvaluationList_Result> IMS_GetIMSEvaluationList(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMS_GetIMSEvaluationList_Result>("IMS_GetIMSEvaluationList", idParameter);
        }
    
        public virtual ObjectResult<IMS_GetIMSIdeaDetails_Result> IMS_GetIMSIdeaDetails(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMS_GetIMSIdeaDetails_Result>("IMS_GetIMSIdeaDetails", idParameter);
        }
    
        public virtual ObjectResult<IMS_GetIMSList_Result> IMS_GetIMSList(string globalId)
        {
            var globalIdParameter = globalId != null ?
                new ObjectParameter("GlobalId", globalId) :
                new ObjectParameter("GlobalId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMS_GetIMSList_Result>("IMS_GetIMSList", globalIdParameter);
        }
    
        public virtual ObjectResult<IMS_GetIMSTrackList_Result> IMS_GetIMSTrackList(string globalid)
        {
            var globalidParameter = globalid != null ?
                new ObjectParameter("globalid", globalid) :
                new ObjectParameter("globalid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMS_GetIMSTrackList_Result>("IMS_GetIMSTrackList", globalidParameter);
        }
    
        public virtual ObjectResult<IMS_GetIMSWinnersList_Result> IMS_GetIMSWinnersList(Nullable<System.DateTime> fromdate, Nullable<System.DateTime> todate)
        {
            var fromdateParameter = fromdate.HasValue ?
                new ObjectParameter("fromdate", fromdate) :
                new ObjectParameter("fromdate", typeof(System.DateTime));
    
            var todateParameter = todate.HasValue ?
                new ObjectParameter("todate", todate) :
                new ObjectParameter("todate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMS_GetIMSWinnersList_Result>("IMS_GetIMSWinnersList", fromdateParameter, todateParameter);
        }
    
        public virtual ObjectResult<IMS_GetQueryList_Result> IMS_GetQueryList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMS_GetQueryList_Result>("IMS_GetQueryList");
        }
    
        public virtual ObjectResult<IMS_GetQueryListByGlobalId_Result> IMS_GetQueryListByGlobalId(string globalId)
        {
            var globalIdParameter = globalId != null ?
                new ObjectParameter("GlobalId", globalId) :
                new ObjectParameter("GlobalId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMS_GetQueryListByGlobalId_Result>("IMS_GetQueryListByGlobalId", globalIdParameter);
        }
    
        public virtual ObjectResult<ims_getsavingsdata_Result> ims_getsavingsdata()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ims_getsavingsdata_Result>("ims_getsavingsdata");
        }
    
        public virtual ObjectResult<IMS_getTeamDetailsIdeaid_Result> IMS_getTeamDetailsIdeaid(Nullable<int> ideaId)
        {
            var ideaIdParameter = ideaId.HasValue ?
                new ObjectParameter("IdeaId", ideaId) :
                new ObjectParameter("IdeaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMS_getTeamDetailsIdeaid_Result>("IMS_getTeamDetailsIdeaid", ideaIdParameter);
        }
    
        public virtual ObjectResult<IMS_getTeamFormationbyIdeaid_Result> IMS_getTeamFormationbyIdeaid(Nullable<int> ideaId)
        {
            var ideaIdParameter = ideaId.HasValue ?
                new ObjectParameter("IdeaId", ideaId) :
                new ObjectParameter("IdeaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMS_getTeamFormationbyIdeaid_Result>("IMS_getTeamFormationbyIdeaid", ideaIdParameter);
        }
    
        public virtual ObjectResult<IMS_IdeaValuedll_Result> IMS_IdeaValuedll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMS_IdeaValuedll_Result>("IMS_IdeaValuedll");
        }
    
        public virtual ObjectResult<IMS_QuerySave_Result> IMS_QuerySave(Nullable<int> id, string queryText, string fileName, string fileSize, string filetype, byte[] fileContent, string base64String, string createdBy, string updatedBy, Nullable<int> freezed, string responseText, string responseBy, string status)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var queryTextParameter = queryText != null ?
                new ObjectParameter("QueryText", queryText) :
                new ObjectParameter("QueryText", typeof(string));
    
            var fileNameParameter = fileName != null ?
                new ObjectParameter("FileName", fileName) :
                new ObjectParameter("FileName", typeof(string));
    
            var fileSizeParameter = fileSize != null ?
                new ObjectParameter("FileSize", fileSize) :
                new ObjectParameter("FileSize", typeof(string));
    
            var filetypeParameter = filetype != null ?
                new ObjectParameter("Filetype", filetype) :
                new ObjectParameter("Filetype", typeof(string));
    
            var fileContentParameter = fileContent != null ?
                new ObjectParameter("FileContent", fileContent) :
                new ObjectParameter("FileContent", typeof(byte[]));
    
            var base64StringParameter = base64String != null ?
                new ObjectParameter("Base64String", base64String) :
                new ObjectParameter("Base64String", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(string));
    
            var freezedParameter = freezed.HasValue ?
                new ObjectParameter("Freezed", freezed) :
                new ObjectParameter("Freezed", typeof(int));
    
            var responseTextParameter = responseText != null ?
                new ObjectParameter("ResponseText", responseText) :
                new ObjectParameter("ResponseText", typeof(string));
    
            var responseByParameter = responseBy != null ?
                new ObjectParameter("ResponseBy", responseBy) :
                new ObjectParameter("ResponseBy", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMS_QuerySave_Result>("IMS_QuerySave", idParameter, queryTextParameter, fileNameParameter, fileSizeParameter, filetypeParameter, fileContentParameter, base64StringParameter, createdByParameter, updatedByParameter, freezedParameter, responseTextParameter, responseByParameter, statusParameter);
        }
    
        public virtual ObjectResult<IMS_Save_Result> IMS_Save(Nullable<int> id, string ideaTitle, string description, Nullable<int> processingStatusId, string globalId, Nullable<int> categoryCode, string evaluationStatus)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var ideaTitleParameter = ideaTitle != null ?
                new ObjectParameter("IdeaTitle", ideaTitle) :
                new ObjectParameter("IdeaTitle", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var processingStatusIdParameter = processingStatusId.HasValue ?
                new ObjectParameter("ProcessingStatusId", processingStatusId) :
                new ObjectParameter("ProcessingStatusId", typeof(int));
    
            var globalIdParameter = globalId != null ?
                new ObjectParameter("GlobalId", globalId) :
                new ObjectParameter("GlobalId", typeof(string));
    
            var categoryCodeParameter = categoryCode.HasValue ?
                new ObjectParameter("CategoryCode", categoryCode) :
                new ObjectParameter("CategoryCode", typeof(int));
    
            var evaluationStatusParameter = evaluationStatus != null ?
                new ObjectParameter("EvaluationStatus", evaluationStatus) :
                new ObjectParameter("EvaluationStatus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMS_Save_Result>("IMS_Save", idParameter, ideaTitleParameter, descriptionParameter, processingStatusIdParameter, globalIdParameter, categoryCodeParameter, evaluationStatusParameter);
        }
    
        public virtual ObjectResult<IMS_SaveAttachment_Result> IMS_SaveAttachment(Nullable<int> ideaId, string globalId, string flieName, Nullable<int> fileLength, string fileType, byte[] fileAttachment, string base64string, string attachmenttype)
        {
            var ideaIdParameter = ideaId.HasValue ?
                new ObjectParameter("IdeaId", ideaId) :
                new ObjectParameter("IdeaId", typeof(int));
    
            var globalIdParameter = globalId != null ?
                new ObjectParameter("GlobalId", globalId) :
                new ObjectParameter("GlobalId", typeof(string));
    
            var flieNameParameter = flieName != null ?
                new ObjectParameter("FlieName", flieName) :
                new ObjectParameter("FlieName", typeof(string));
    
            var fileLengthParameter = fileLength.HasValue ?
                new ObjectParameter("FileLength", fileLength) :
                new ObjectParameter("FileLength", typeof(int));
    
            var fileTypeParameter = fileType != null ?
                new ObjectParameter("FileType", fileType) :
                new ObjectParameter("FileType", typeof(string));
    
            var fileAttachmentParameter = fileAttachment != null ?
                new ObjectParameter("FileAttachment", fileAttachment) :
                new ObjectParameter("FileAttachment", typeof(byte[]));
    
            var base64stringParameter = base64string != null ?
                new ObjectParameter("Base64string", base64string) :
                new ObjectParameter("Base64string", typeof(string));
    
            var attachmenttypeParameter = attachmenttype != null ?
                new ObjectParameter("attachmenttype", attachmenttype) :
                new ObjectParameter("attachmenttype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMS_SaveAttachment_Result>("IMS_SaveAttachment", ideaIdParameter, globalIdParameter, flieNameParameter, fileLengthParameter, fileTypeParameter, fileAttachmentParameter, base64stringParameter, attachmenttypeParameter);
        }
    
        public virtual ObjectResult<IMS_SaveEvaluation_Result> IMS_SaveEvaluation(Nullable<int> id, string globalId, string status, string remarks, string onbehalfselectionid, string onbehalfselectionremarks)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var globalIdParameter = globalId != null ?
                new ObjectParameter("GlobalId", globalId) :
                new ObjectParameter("GlobalId", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var remarksParameter = remarks != null ?
                new ObjectParameter("remarks", remarks) :
                new ObjectParameter("remarks", typeof(string));
    
            var onbehalfselectionidParameter = onbehalfselectionid != null ?
                new ObjectParameter("onbehalfselectionid", onbehalfselectionid) :
                new ObjectParameter("onbehalfselectionid", typeof(string));
    
            var onbehalfselectionremarksParameter = onbehalfselectionremarks != null ?
                new ObjectParameter("onbehalfselectionremarks", onbehalfselectionremarks) :
                new ObjectParameter("onbehalfselectionremarks", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMS_SaveEvaluation_Result>("IMS_SaveEvaluation", idParameter, globalIdParameter, statusParameter, remarksParameter, onbehalfselectionidParameter, onbehalfselectionremarksParameter);
        }
    
        public virtual ObjectResult<IMS_SaveIdeaScore_Result> IMS_SaveIdeaScore(Nullable<int> id, string globalId, Nullable<int> eOI_Score, Nullable<int> cSP_Score, string remarks, string onbehalfscoringid, string onbehalfscoringremarks)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var globalIdParameter = globalId != null ?
                new ObjectParameter("GlobalId", globalId) :
                new ObjectParameter("GlobalId", typeof(string));
    
            var eOI_ScoreParameter = eOI_Score.HasValue ?
                new ObjectParameter("EOI_Score", eOI_Score) :
                new ObjectParameter("EOI_Score", typeof(int));
    
            var cSP_ScoreParameter = cSP_Score.HasValue ?
                new ObjectParameter("CSP_Score", cSP_Score) :
                new ObjectParameter("CSP_Score", typeof(int));
    
            var remarksParameter = remarks != null ?
                new ObjectParameter("remarks", remarks) :
                new ObjectParameter("remarks", typeof(string));
    
            var onbehalfscoringidParameter = onbehalfscoringid != null ?
                new ObjectParameter("onbehalfscoringid", onbehalfscoringid) :
                new ObjectParameter("onbehalfscoringid", typeof(string));
    
            var onbehalfscoringremarksParameter = onbehalfscoringremarks != null ?
                new ObjectParameter("onbehalfscoringremarks", onbehalfscoringremarks) :
                new ObjectParameter("onbehalfscoringremarks", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMS_SaveIdeaScore_Result>("IMS_SaveIdeaScore", idParameter, globalIdParameter, eOI_ScoreParameter, cSP_ScoreParameter, remarksParameter, onbehalfscoringidParameter, onbehalfscoringremarksParameter);
        }
    
        public virtual ObjectResult<IMS_SaveIdeaShortList_Result> IMS_SaveIdeaShortList(Nullable<int> id, string globalId, string remarks, Nullable<bool> isboosted)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var globalIdParameter = globalId != null ?
                new ObjectParameter("GlobalId", globalId) :
                new ObjectParameter("GlobalId", typeof(string));
    
            var remarksParameter = remarks != null ?
                new ObjectParameter("Remarks", remarks) :
                new ObjectParameter("Remarks", typeof(string));
    
            var isboostedParameter = isboosted.HasValue ?
                new ObjectParameter("isboosted", isboosted) :
                new ObjectParameter("isboosted", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMS_SaveIdeaShortList_Result>("IMS_SaveIdeaShortList", idParameter, globalIdParameter, remarksParameter, isboostedParameter);
        }
    
        public virtual ObjectResult<IMS_SaveIdeaValue_Result> IMS_SaveIdeaValue(Nullable<int> ideaId, Nullable<int> ideaValueId, string ideaValueText, string globalId)
        {
            var ideaIdParameter = ideaId.HasValue ?
                new ObjectParameter("IdeaId", ideaId) :
                new ObjectParameter("IdeaId", typeof(int));
    
            var ideaValueIdParameter = ideaValueId.HasValue ?
                new ObjectParameter("IdeaValueId", ideaValueId) :
                new ObjectParameter("IdeaValueId", typeof(int));
    
            var ideaValueTextParameter = ideaValueText != null ?
                new ObjectParameter("IdeaValueText", ideaValueText) :
                new ObjectParameter("IdeaValueText", typeof(string));
    
            var globalIdParameter = globalId != null ?
                new ObjectParameter("GlobalId", globalId) :
                new ObjectParameter("GlobalId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMS_SaveIdeaValue_Result>("IMS_SaveIdeaValue", ideaIdParameter, ideaValueIdParameter, ideaValueTextParameter, globalIdParameter);
        }
    
        public virtual ObjectResult<IMS_SaveIdeawinner_Result> IMS_SaveIdeawinner(Nullable<int> id, string globalId, string remarks)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var globalIdParameter = globalId != null ?
                new ObjectParameter("GlobalId", globalId) :
                new ObjectParameter("GlobalId", typeof(string));
    
            var remarksParameter = remarks != null ?
                new ObjectParameter("Remarks", remarks) :
                new ObjectParameter("Remarks", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMS_SaveIdeawinner_Result>("IMS_SaveIdeawinner", idParameter, globalIdParameter, remarksParameter);
        }
    
        public virtual ObjectResult<IMS_SaveMonthsSavings_Result> IMS_SaveMonthsSavings(Nullable<int> id, Nullable<int> ideaId, Nullable<decimal> twelveMonthsSavings, Nullable<decimal> paybackPeriod, Nullable<decimal> m1, Nullable<decimal> m2, Nullable<decimal> m3, Nullable<decimal> m4, Nullable<decimal> m5, Nullable<decimal> m6, Nullable<decimal> m7, Nullable<decimal> m8, Nullable<decimal> m9, Nullable<decimal> m10, Nullable<decimal> m11, Nullable<decimal> m12, string globalId)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var ideaIdParameter = ideaId.HasValue ?
                new ObjectParameter("IdeaId", ideaId) :
                new ObjectParameter("IdeaId", typeof(int));
    
            var twelveMonthsSavingsParameter = twelveMonthsSavings.HasValue ?
                new ObjectParameter("TwelveMonthsSavings", twelveMonthsSavings) :
                new ObjectParameter("TwelveMonthsSavings", typeof(decimal));
    
            var paybackPeriodParameter = paybackPeriod.HasValue ?
                new ObjectParameter("PaybackPeriod", paybackPeriod) :
                new ObjectParameter("PaybackPeriod", typeof(decimal));
    
            var m1Parameter = m1.HasValue ?
                new ObjectParameter("M1", m1) :
                new ObjectParameter("M1", typeof(decimal));
    
            var m2Parameter = m2.HasValue ?
                new ObjectParameter("M2", m2) :
                new ObjectParameter("M2", typeof(decimal));
    
            var m3Parameter = m3.HasValue ?
                new ObjectParameter("M3", m3) :
                new ObjectParameter("M3", typeof(decimal));
    
            var m4Parameter = m4.HasValue ?
                new ObjectParameter("M4", m4) :
                new ObjectParameter("M4", typeof(decimal));
    
            var m5Parameter = m5.HasValue ?
                new ObjectParameter("M5", m5) :
                new ObjectParameter("M5", typeof(decimal));
    
            var m6Parameter = m6.HasValue ?
                new ObjectParameter("M6", m6) :
                new ObjectParameter("M6", typeof(decimal));
    
            var m7Parameter = m7.HasValue ?
                new ObjectParameter("M7", m7) :
                new ObjectParameter("M7", typeof(decimal));
    
            var m8Parameter = m8.HasValue ?
                new ObjectParameter("M8", m8) :
                new ObjectParameter("M8", typeof(decimal));
    
            var m9Parameter = m9.HasValue ?
                new ObjectParameter("M9", m9) :
                new ObjectParameter("M9", typeof(decimal));
    
            var m10Parameter = m10.HasValue ?
                new ObjectParameter("M10", m10) :
                new ObjectParameter("M10", typeof(decimal));
    
            var m11Parameter = m11.HasValue ?
                new ObjectParameter("M11", m11) :
                new ObjectParameter("M11", typeof(decimal));
    
            var m12Parameter = m12.HasValue ?
                new ObjectParameter("M12", m12) :
                new ObjectParameter("M12", typeof(decimal));
    
            var globalIdParameter = globalId != null ?
                new ObjectParameter("GlobalId", globalId) :
                new ObjectParameter("GlobalId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMS_SaveMonthsSavings_Result>("IMS_SaveMonthsSavings", idParameter, ideaIdParameter, twelveMonthsSavingsParameter, paybackPeriodParameter, m1Parameter, m2Parameter, m3Parameter, m4Parameter, m5Parameter, m6Parameter, m7Parameter, m8Parameter, m9Parameter, m10Parameter, m11Parameter, m12Parameter, globalIdParameter);
        }
    
        public virtual ObjectResult<IMS_SaveTeamFormation_Result> IMS_SaveTeamFormation(Nullable<int> id, Nullable<int> ideaId, string member, string globalId, string membertype)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var ideaIdParameter = ideaId.HasValue ?
                new ObjectParameter("IdeaId", ideaId) :
                new ObjectParameter("IdeaId", typeof(int));
    
            var memberParameter = member != null ?
                new ObjectParameter("Member", member) :
                new ObjectParameter("Member", typeof(string));
    
            var globalIdParameter = globalId != null ?
                new ObjectParameter("GlobalId", globalId) :
                new ObjectParameter("GlobalId", typeof(string));
    
            var membertypeParameter = membertype != null ?
                new ObjectParameter("membertype", membertype) :
                new ObjectParameter("membertype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMS_SaveTeamFormation_Result>("IMS_SaveTeamFormation", idParameter, ideaIdParameter, memberParameter, globalIdParameter, membertypeParameter);
        }
    
        public virtual ObjectResult<IMS_Savetracking_Result> IMS_Savetracking(Nullable<int> id, Nullable<int> ideaId, Nullable<decimal> twelveMonthsSavings, Nullable<decimal> paybackPeriod, Nullable<decimal> m1, Nullable<decimal> m2, Nullable<decimal> m3, Nullable<decimal> m4, Nullable<decimal> m5, Nullable<decimal> m6, Nullable<decimal> m7, Nullable<decimal> m8, Nullable<decimal> m9, Nullable<decimal> m10, Nullable<decimal> m11, Nullable<decimal> m12, string globalId, Nullable<System.DateTime> actualimplementationstarts, Nullable<System.DateTime> actualimplementationends, Nullable<System.DateTime> actualsavingstarts, Nullable<decimal> implementationperiod)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var ideaIdParameter = ideaId.HasValue ?
                new ObjectParameter("IdeaId", ideaId) :
                new ObjectParameter("IdeaId", typeof(int));
    
            var twelveMonthsSavingsParameter = twelveMonthsSavings.HasValue ?
                new ObjectParameter("TwelveMonthsSavings", twelveMonthsSavings) :
                new ObjectParameter("TwelveMonthsSavings", typeof(decimal));
    
            var paybackPeriodParameter = paybackPeriod.HasValue ?
                new ObjectParameter("PaybackPeriod", paybackPeriod) :
                new ObjectParameter("PaybackPeriod", typeof(decimal));
    
            var m1Parameter = m1.HasValue ?
                new ObjectParameter("M1", m1) :
                new ObjectParameter("M1", typeof(decimal));
    
            var m2Parameter = m2.HasValue ?
                new ObjectParameter("M2", m2) :
                new ObjectParameter("M2", typeof(decimal));
    
            var m3Parameter = m3.HasValue ?
                new ObjectParameter("M3", m3) :
                new ObjectParameter("M3", typeof(decimal));
    
            var m4Parameter = m4.HasValue ?
                new ObjectParameter("M4", m4) :
                new ObjectParameter("M4", typeof(decimal));
    
            var m5Parameter = m5.HasValue ?
                new ObjectParameter("M5", m5) :
                new ObjectParameter("M5", typeof(decimal));
    
            var m6Parameter = m6.HasValue ?
                new ObjectParameter("M6", m6) :
                new ObjectParameter("M6", typeof(decimal));
    
            var m7Parameter = m7.HasValue ?
                new ObjectParameter("M7", m7) :
                new ObjectParameter("M7", typeof(decimal));
    
            var m8Parameter = m8.HasValue ?
                new ObjectParameter("M8", m8) :
                new ObjectParameter("M8", typeof(decimal));
    
            var m9Parameter = m9.HasValue ?
                new ObjectParameter("M9", m9) :
                new ObjectParameter("M9", typeof(decimal));
    
            var m10Parameter = m10.HasValue ?
                new ObjectParameter("M10", m10) :
                new ObjectParameter("M10", typeof(decimal));
    
            var m11Parameter = m11.HasValue ?
                new ObjectParameter("M11", m11) :
                new ObjectParameter("M11", typeof(decimal));
    
            var m12Parameter = m12.HasValue ?
                new ObjectParameter("M12", m12) :
                new ObjectParameter("M12", typeof(decimal));
    
            var globalIdParameter = globalId != null ?
                new ObjectParameter("GlobalId", globalId) :
                new ObjectParameter("GlobalId", typeof(string));
    
            var actualimplementationstartsParameter = actualimplementationstarts.HasValue ?
                new ObjectParameter("actualimplementationstarts", actualimplementationstarts) :
                new ObjectParameter("actualimplementationstarts", typeof(System.DateTime));
    
            var actualimplementationendsParameter = actualimplementationends.HasValue ?
                new ObjectParameter("actualimplementationends", actualimplementationends) :
                new ObjectParameter("actualimplementationends", typeof(System.DateTime));
    
            var actualsavingstartsParameter = actualsavingstarts.HasValue ?
                new ObjectParameter("actualsavingstarts", actualsavingstarts) :
                new ObjectParameter("actualsavingstarts", typeof(System.DateTime));
    
            var implementationperiodParameter = implementationperiod.HasValue ?
                new ObjectParameter("implementationperiod", implementationperiod) :
                new ObjectParameter("implementationperiod", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMS_Savetracking_Result>("IMS_Savetracking", idParameter, ideaIdParameter, twelveMonthsSavingsParameter, paybackPeriodParameter, m1Parameter, m2Parameter, m3Parameter, m4Parameter, m5Parameter, m6Parameter, m7Parameter, m8Parameter, m9Parameter, m10Parameter, m11Parameter, m12Parameter, globalIdParameter, actualimplementationstartsParameter, actualimplementationendsParameter, actualsavingstartsParameter, implementationperiodParameter);
        }
    
        public virtual ObjectResult<IMS_Savetracking_v1_Result> IMS_Savetracking_v1(Nullable<int> id, Nullable<int> ideaId, Nullable<decimal> twelveMonthsSavings, Nullable<decimal> paybackPeriod, Nullable<decimal> m1, Nullable<decimal> m2, Nullable<decimal> m3, Nullable<decimal> m4, Nullable<decimal> m5, Nullable<decimal> m6, Nullable<decimal> m7, Nullable<decimal> m8, Nullable<decimal> m9, Nullable<decimal> m10, Nullable<decimal> m11, Nullable<decimal> m12, string globalId, Nullable<System.DateTime> actualimplementationstarts, Nullable<System.DateTime> actualimplementationends, Nullable<System.DateTime> actualsavingstarts, Nullable<decimal> implementationperiod, Nullable<decimal> incentiveearned)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var ideaIdParameter = ideaId.HasValue ?
                new ObjectParameter("IdeaId", ideaId) :
                new ObjectParameter("IdeaId", typeof(int));
    
            var twelveMonthsSavingsParameter = twelveMonthsSavings.HasValue ?
                new ObjectParameter("TwelveMonthsSavings", twelveMonthsSavings) :
                new ObjectParameter("TwelveMonthsSavings", typeof(decimal));
    
            var paybackPeriodParameter = paybackPeriod.HasValue ?
                new ObjectParameter("PaybackPeriod", paybackPeriod) :
                new ObjectParameter("PaybackPeriod", typeof(decimal));
    
            var m1Parameter = m1.HasValue ?
                new ObjectParameter("M1", m1) :
                new ObjectParameter("M1", typeof(decimal));
    
            var m2Parameter = m2.HasValue ?
                new ObjectParameter("M2", m2) :
                new ObjectParameter("M2", typeof(decimal));
    
            var m3Parameter = m3.HasValue ?
                new ObjectParameter("M3", m3) :
                new ObjectParameter("M3", typeof(decimal));
    
            var m4Parameter = m4.HasValue ?
                new ObjectParameter("M4", m4) :
                new ObjectParameter("M4", typeof(decimal));
    
            var m5Parameter = m5.HasValue ?
                new ObjectParameter("M5", m5) :
                new ObjectParameter("M5", typeof(decimal));
    
            var m6Parameter = m6.HasValue ?
                new ObjectParameter("M6", m6) :
                new ObjectParameter("M6", typeof(decimal));
    
            var m7Parameter = m7.HasValue ?
                new ObjectParameter("M7", m7) :
                new ObjectParameter("M7", typeof(decimal));
    
            var m8Parameter = m8.HasValue ?
                new ObjectParameter("M8", m8) :
                new ObjectParameter("M8", typeof(decimal));
    
            var m9Parameter = m9.HasValue ?
                new ObjectParameter("M9", m9) :
                new ObjectParameter("M9", typeof(decimal));
    
            var m10Parameter = m10.HasValue ?
                new ObjectParameter("M10", m10) :
                new ObjectParameter("M10", typeof(decimal));
    
            var m11Parameter = m11.HasValue ?
                new ObjectParameter("M11", m11) :
                new ObjectParameter("M11", typeof(decimal));
    
            var m12Parameter = m12.HasValue ?
                new ObjectParameter("M12", m12) :
                new ObjectParameter("M12", typeof(decimal));
    
            var globalIdParameter = globalId != null ?
                new ObjectParameter("GlobalId", globalId) :
                new ObjectParameter("GlobalId", typeof(string));
    
            var actualimplementationstartsParameter = actualimplementationstarts.HasValue ?
                new ObjectParameter("actualimplementationstarts", actualimplementationstarts) :
                new ObjectParameter("actualimplementationstarts", typeof(System.DateTime));
    
            var actualimplementationendsParameter = actualimplementationends.HasValue ?
                new ObjectParameter("actualimplementationends", actualimplementationends) :
                new ObjectParameter("actualimplementationends", typeof(System.DateTime));
    
            var actualsavingstartsParameter = actualsavingstarts.HasValue ?
                new ObjectParameter("actualsavingstarts", actualsavingstarts) :
                new ObjectParameter("actualsavingstarts", typeof(System.DateTime));
    
            var implementationperiodParameter = implementationperiod.HasValue ?
                new ObjectParameter("implementationperiod", implementationperiod) :
                new ObjectParameter("implementationperiod", typeof(decimal));
    
            var incentiveearnedParameter = incentiveearned.HasValue ?
                new ObjectParameter("incentiveearned", incentiveearned) :
                new ObjectParameter("incentiveearned", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMS_Savetracking_v1_Result>("IMS_Savetracking_v1", idParameter, ideaIdParameter, twelveMonthsSavingsParameter, paybackPeriodParameter, m1Parameter, m2Parameter, m3Parameter, m4Parameter, m5Parameter, m6Parameter, m7Parameter, m8Parameter, m9Parameter, m10Parameter, m11Parameter, m12Parameter, globalIdParameter, actualimplementationstartsParameter, actualimplementationendsParameter, actualsavingstartsParameter, implementationperiodParameter, incentiveearnedParameter);
        }
    
        public virtual ObjectResult<insertCollaborators_Result> insertCollaborators(Nullable<int> id, Nullable<int> ideaId, string collaborator_globalid, string createdBy)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var ideaIdParameter = ideaId.HasValue ?
                new ObjectParameter("IdeaId", ideaId) :
                new ObjectParameter("IdeaId", typeof(int));
    
            var collaborator_globalidParameter = collaborator_globalid != null ?
                new ObjectParameter("collaborator_globalid", collaborator_globalid) :
                new ObjectParameter("collaborator_globalid", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<insertCollaborators_Result>("insertCollaborators", idParameter, ideaIdParameter, collaborator_globalidParameter, createdByParameter);
        }
    
        public virtual ObjectResult<insertemployeesroleandapprover_Result> insertemployeesroleandapprover(Nullable<int> id, string name, string email, string adid, Nullable<int> userid, Nullable<int> roleid, Nullable<int> createdby, string globalid, Nullable<int> locationid, Nullable<int> departmentid, Nullable<int> subdepartmentid, string managerid, string hodid, string verifier, string approver, string departmentname, string subdepartmentname, string ipaddress, string remarks, string savetype)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var adidParameter = adid != null ?
                new ObjectParameter("adid", adid) :
                new ObjectParameter("adid", typeof(string));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var roleidParameter = roleid.HasValue ?
                new ObjectParameter("roleid", roleid) :
                new ObjectParameter("roleid", typeof(int));
    
            var createdbyParameter = createdby.HasValue ?
                new ObjectParameter("createdby", createdby) :
                new ObjectParameter("createdby", typeof(int));
    
            var globalidParameter = globalid != null ?
                new ObjectParameter("globalid", globalid) :
                new ObjectParameter("globalid", typeof(string));
    
            var locationidParameter = locationid.HasValue ?
                new ObjectParameter("locationid", locationid) :
                new ObjectParameter("locationid", typeof(int));
    
            var departmentidParameter = departmentid.HasValue ?
                new ObjectParameter("departmentid", departmentid) :
                new ObjectParameter("departmentid", typeof(int));
    
            var subdepartmentidParameter = subdepartmentid.HasValue ?
                new ObjectParameter("subdepartmentid", subdepartmentid) :
                new ObjectParameter("subdepartmentid", typeof(int));
    
            var manageridParameter = managerid != null ?
                new ObjectParameter("managerid", managerid) :
                new ObjectParameter("managerid", typeof(string));
    
            var hodidParameter = hodid != null ?
                new ObjectParameter("hodid", hodid) :
                new ObjectParameter("hodid", typeof(string));
    
            var verifierParameter = verifier != null ?
                new ObjectParameter("verifier", verifier) :
                new ObjectParameter("verifier", typeof(string));
    
            var approverParameter = approver != null ?
                new ObjectParameter("approver", approver) :
                new ObjectParameter("approver", typeof(string));
    
            var departmentnameParameter = departmentname != null ?
                new ObjectParameter("departmentname", departmentname) :
                new ObjectParameter("departmentname", typeof(string));
    
            var subdepartmentnameParameter = subdepartmentname != null ?
                new ObjectParameter("subdepartmentname", subdepartmentname) :
                new ObjectParameter("subdepartmentname", typeof(string));
    
            var ipaddressParameter = ipaddress != null ?
                new ObjectParameter("ipaddress", ipaddress) :
                new ObjectParameter("ipaddress", typeof(string));
    
            var remarksParameter = remarks != null ?
                new ObjectParameter("remarks", remarks) :
                new ObjectParameter("remarks", typeof(string));
    
            var savetypeParameter = savetype != null ?
                new ObjectParameter("savetype", savetype) :
                new ObjectParameter("savetype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<insertemployeesroleandapprover_Result>("insertemployeesroleandapprover", idParameter, nameParameter, emailParameter, adidParameter, useridParameter, roleidParameter, createdbyParameter, globalidParameter, locationidParameter, departmentidParameter, subdepartmentidParameter, manageridParameter, hodidParameter, verifierParameter, approverParameter, departmentnameParameter, subdepartmentnameParameter, ipaddressParameter, remarksParameter, savetypeParameter);
        }
    
        public virtual ObjectResult<insertemployeesroleandapprovernew_Result> insertemployeesroleandapprovernew(Nullable<int> id, string name, string email, string adid, Nullable<int> userid, Nullable<int> roleid, Nullable<int> createdby, string globalid, Nullable<int> locationid, Nullable<int> departmentid, Nullable<int> subdepartmentid, string managerid, string hodid, string departmentname, string subdepartmentname, string ipaddress, string remarks)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var adidParameter = adid != null ?
                new ObjectParameter("adid", adid) :
                new ObjectParameter("adid", typeof(string));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var roleidParameter = roleid.HasValue ?
                new ObjectParameter("roleid", roleid) :
                new ObjectParameter("roleid", typeof(int));
    
            var createdbyParameter = createdby.HasValue ?
                new ObjectParameter("createdby", createdby) :
                new ObjectParameter("createdby", typeof(int));
    
            var globalidParameter = globalid != null ?
                new ObjectParameter("globalid", globalid) :
                new ObjectParameter("globalid", typeof(string));
    
            var locationidParameter = locationid.HasValue ?
                new ObjectParameter("locationid", locationid) :
                new ObjectParameter("locationid", typeof(int));
    
            var departmentidParameter = departmentid.HasValue ?
                new ObjectParameter("departmentid", departmentid) :
                new ObjectParameter("departmentid", typeof(int));
    
            var subdepartmentidParameter = subdepartmentid.HasValue ?
                new ObjectParameter("subdepartmentid", subdepartmentid) :
                new ObjectParameter("subdepartmentid", typeof(int));
    
            var manageridParameter = managerid != null ?
                new ObjectParameter("managerid", managerid) :
                new ObjectParameter("managerid", typeof(string));
    
            var hodidParameter = hodid != null ?
                new ObjectParameter("hodid", hodid) :
                new ObjectParameter("hodid", typeof(string));
    
            var departmentnameParameter = departmentname != null ?
                new ObjectParameter("departmentname", departmentname) :
                new ObjectParameter("departmentname", typeof(string));
    
            var subdepartmentnameParameter = subdepartmentname != null ?
                new ObjectParameter("subdepartmentname", subdepartmentname) :
                new ObjectParameter("subdepartmentname", typeof(string));
    
            var ipaddressParameter = ipaddress != null ?
                new ObjectParameter("ipaddress", ipaddress) :
                new ObjectParameter("ipaddress", typeof(string));
    
            var remarksParameter = remarks != null ?
                new ObjectParameter("remarks", remarks) :
                new ObjectParameter("remarks", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<insertemployeesroleandapprovernew_Result>("insertemployeesroleandapprovernew", idParameter, nameParameter, emailParameter, adidParameter, useridParameter, roleidParameter, createdbyParameter, globalidParameter, locationidParameter, departmentidParameter, subdepartmentidParameter, manageridParameter, hodidParameter, departmentnameParameter, subdepartmentnameParameter, ipaddressParameter, remarksParameter);
        }
    
        public virtual int inserterrorlog(Nullable<int> userid, string module, string description, string activity)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var moduleParameter = module != null ?
                new ObjectParameter("module", module) :
                new ObjectParameter("module", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var activityParameter = activity != null ?
                new ObjectParameter("activity", activity) :
                new ObjectParameter("activity", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("inserterrorlog", useridParameter, moduleParameter, descriptionParameter, activityParameter);
        }
    
        public virtual int InsertLocation(string addressline1, string addressline2, string addressline3, string addressline4, string licencenumber, string serverprinterip, string localprinterip)
        {
            var addressline1Parameter = addressline1 != null ?
                new ObjectParameter("addressline1", addressline1) :
                new ObjectParameter("addressline1", typeof(string));
    
            var addressline2Parameter = addressline2 != null ?
                new ObjectParameter("addressline2", addressline2) :
                new ObjectParameter("addressline2", typeof(string));
    
            var addressline3Parameter = addressline3 != null ?
                new ObjectParameter("addressline3", addressline3) :
                new ObjectParameter("addressline3", typeof(string));
    
            var addressline4Parameter = addressline4 != null ?
                new ObjectParameter("addressline4", addressline4) :
                new ObjectParameter("addressline4", typeof(string));
    
            var licencenumberParameter = licencenumber != null ?
                new ObjectParameter("licencenumber", licencenumber) :
                new ObjectParameter("licencenumber", typeof(string));
    
            var serverprinteripParameter = serverprinterip != null ?
                new ObjectParameter("serverprinterip", serverprinterip) :
                new ObjectParameter("serverprinterip", typeof(string));
    
            var localprinteripParameter = localprinterip != null ?
                new ObjectParameter("localprinterip", localprinterip) :
                new ObjectParameter("localprinterip", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertLocation", addressline1Parameter, addressline2Parameter, addressline3Parameter, addressline4Parameter, licencenumberParameter, serverprinteripParameter, localprinteripParameter);
        }
    
        public virtual int insertrolewisemenu(Nullable<int> menuid, Nullable<int> roleid, Nullable<int> permissionid, Nullable<int> createdby, string ipaddress, string remarks, ObjectParameter @return)
        {
            var menuidParameter = menuid.HasValue ?
                new ObjectParameter("menuid", menuid) :
                new ObjectParameter("menuid", typeof(int));
    
            var roleidParameter = roleid.HasValue ?
                new ObjectParameter("roleid", roleid) :
                new ObjectParameter("roleid", typeof(int));
    
            var permissionidParameter = permissionid.HasValue ?
                new ObjectParameter("permissionid", permissionid) :
                new ObjectParameter("permissionid", typeof(int));
    
            var createdbyParameter = createdby.HasValue ?
                new ObjectParameter("createdby", createdby) :
                new ObjectParameter("createdby", typeof(int));
    
            var ipaddressParameter = ipaddress != null ?
                new ObjectParameter("ipaddress", ipaddress) :
                new ObjectParameter("ipaddress", typeof(string));
    
            var remarksParameter = remarks != null ?
                new ObjectParameter("remarks", remarks) :
                new ObjectParameter("remarks", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertrolewisemenu", menuidParameter, roleidParameter, permissionidParameter, createdbyParameter, ipaddressParameter, remarksParameter, @return);
        }
    
        public virtual int insertrolewisemenuhistory(Nullable<int> menuid, Nullable<int> roleid, Nullable<int> permissionid, Nullable<int> createdby, Nullable<System.DateTime> createdon, Nullable<int> historyby, Nullable<int> deletedid, ObjectParameter @return)
        {
            var menuidParameter = menuid.HasValue ?
                new ObjectParameter("menuid", menuid) :
                new ObjectParameter("menuid", typeof(int));
    
            var roleidParameter = roleid.HasValue ?
                new ObjectParameter("roleid", roleid) :
                new ObjectParameter("roleid", typeof(int));
    
            var permissionidParameter = permissionid.HasValue ?
                new ObjectParameter("permissionid", permissionid) :
                new ObjectParameter("permissionid", typeof(int));
    
            var createdbyParameter = createdby.HasValue ?
                new ObjectParameter("createdby", createdby) :
                new ObjectParameter("createdby", typeof(int));
    
            var createdonParameter = createdon.HasValue ?
                new ObjectParameter("createdon", createdon) :
                new ObjectParameter("createdon", typeof(System.DateTime));
    
            var historybyParameter = historyby.HasValue ?
                new ObjectParameter("historyby", historyby) :
                new ObjectParameter("historyby", typeof(int));
    
            var deletedidParameter = deletedid.HasValue ?
                new ObjectParameter("deletedid", deletedid) :
                new ObjectParameter("deletedid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertrolewisemenuhistory", menuidParameter, roleidParameter, permissionidParameter, createdbyParameter, createdonParameter, historybyParameter, deletedidParameter, @return);
        }
    
        public virtual int insertsysteminfo(Nullable<int> userid, string module, string activity)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var moduleParameter = module != null ?
                new ObjectParameter("module", module) :
                new ObjectParameter("module", typeof(string));
    
            var activityParameter = activity != null ?
                new ObjectParameter("activity", activity) :
                new ObjectParameter("activity", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertsysteminfo", useridParameter, moduleParameter, activityParameter);
        }
    
        public virtual int insertupdatemenu(Nullable<int> id, string name, string menuicon, string menuurl, Nullable<int> parentid, Nullable<int> createdby, string clickmode, string ipaddress, string remarks, ObjectParameter @return)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var menuiconParameter = menuicon != null ?
                new ObjectParameter("menuicon", menuicon) :
                new ObjectParameter("menuicon", typeof(string));
    
            var menuurlParameter = menuurl != null ?
                new ObjectParameter("menuurl", menuurl) :
                new ObjectParameter("menuurl", typeof(string));
    
            var parentidParameter = parentid.HasValue ?
                new ObjectParameter("parentid", parentid) :
                new ObjectParameter("parentid", typeof(int));
    
            var createdbyParameter = createdby.HasValue ?
                new ObjectParameter("createdby", createdby) :
                new ObjectParameter("createdby", typeof(int));
    
            var clickmodeParameter = clickmode != null ?
                new ObjectParameter("clickmode", clickmode) :
                new ObjectParameter("clickmode", typeof(string));
    
            var ipaddressParameter = ipaddress != null ?
                new ObjectParameter("ipaddress", ipaddress) :
                new ObjectParameter("ipaddress", typeof(string));
    
            var remarksParameter = remarks != null ?
                new ObjectParameter("remarks", remarks) :
                new ObjectParameter("remarks", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertupdatemenu", idParameter, nameParameter, menuiconParameter, menuurlParameter, parentidParameter, createdbyParameter, clickmodeParameter, ipaddressParameter, remarksParameter, @return);
        }
    
        public virtual int insertupdaterole(Nullable<int> id, string name, Nullable<int> createdby, string clickmode, string ipaddress, string remarks, ObjectParameter @return)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var createdbyParameter = createdby.HasValue ?
                new ObjectParameter("createdby", createdby) :
                new ObjectParameter("createdby", typeof(int));
    
            var clickmodeParameter = clickmode != null ?
                new ObjectParameter("clickmode", clickmode) :
                new ObjectParameter("clickmode", typeof(string));
    
            var ipaddressParameter = ipaddress != null ?
                new ObjectParameter("ipaddress", ipaddress) :
                new ObjectParameter("ipaddress", typeof(string));
    
            var remarksParameter = remarks != null ?
                new ObjectParameter("remarks", remarks) :
                new ObjectParameter("remarks", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertupdaterole", idParameter, nameParameter, createdbyParameter, clickmodeParameter, ipaddressParameter, remarksParameter, @return);
        }
    
        public virtual int insertuserwiserole_audit(Nullable<int> userid, Nullable<int> roleid, Nullable<int> createdby, Nullable<System.DateTime> createdon, Nullable<int> updatedby, Nullable<System.DateTime> updatedon, Nullable<bool> freezed, Nullable<int> historyid, Nullable<int> historyby, string ipaddress, string activity, string remarks, ObjectParameter @return)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var roleidParameter = roleid.HasValue ?
                new ObjectParameter("roleid", roleid) :
                new ObjectParameter("roleid", typeof(int));
    
            var createdbyParameter = createdby.HasValue ?
                new ObjectParameter("createdby", createdby) :
                new ObjectParameter("createdby", typeof(int));
    
            var createdonParameter = createdon.HasValue ?
                new ObjectParameter("createdon", createdon) :
                new ObjectParameter("createdon", typeof(System.DateTime));
    
            var updatedbyParameter = updatedby.HasValue ?
                new ObjectParameter("updatedby", updatedby) :
                new ObjectParameter("updatedby", typeof(int));
    
            var updatedonParameter = updatedon.HasValue ?
                new ObjectParameter("updatedon", updatedon) :
                new ObjectParameter("updatedon", typeof(System.DateTime));
    
            var freezedParameter = freezed.HasValue ?
                new ObjectParameter("freezed", freezed) :
                new ObjectParameter("freezed", typeof(bool));
    
            var historyidParameter = historyid.HasValue ?
                new ObjectParameter("historyid", historyid) :
                new ObjectParameter("historyid", typeof(int));
    
            var historybyParameter = historyby.HasValue ?
                new ObjectParameter("historyby", historyby) :
                new ObjectParameter("historyby", typeof(int));
    
            var ipaddressParameter = ipaddress != null ?
                new ObjectParameter("ipaddress", ipaddress) :
                new ObjectParameter("ipaddress", typeof(string));
    
            var activityParameter = activity != null ?
                new ObjectParameter("activity", activity) :
                new ObjectParameter("activity", typeof(string));
    
            var remarksParameter = remarks != null ?
                new ObjectParameter("remarks", remarks) :
                new ObjectParameter("remarks", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertuserwiserole_audit", useridParameter, roleidParameter, createdbyParameter, createdonParameter, updatedbyParameter, updatedonParameter, freezedParameter, historyidParameter, historybyParameter, ipaddressParameter, activityParameter, remarksParameter, @return);
        }
    
        public virtual ObjectResult<removeCollaborators_Result> removeCollaborators(Nullable<int> ideaId, string createdBy)
        {
            var ideaIdParameter = ideaId.HasValue ?
                new ObjectParameter("IdeaId", ideaId) :
                new ObjectParameter("IdeaId", typeof(int));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<removeCollaborators_Result>("removeCollaborators", ideaIdParameter, createdByParameter);
        }
    
        public virtual int removeRoleWiseMenuByID(Nullable<int> id, Nullable<int> updatedby, string ipaddress, string remarks, ObjectParameter @return)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var updatedbyParameter = updatedby.HasValue ?
                new ObjectParameter("updatedby", updatedby) :
                new ObjectParameter("updatedby", typeof(int));
    
            var ipaddressParameter = ipaddress != null ?
                new ObjectParameter("ipaddress", ipaddress) :
                new ObjectParameter("ipaddress", typeof(string));
    
            var remarksParameter = remarks != null ?
                new ObjectParameter("remarks", remarks) :
                new ObjectParameter("remarks", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("removeRoleWiseMenuByID", idParameter, updatedbyParameter, ipaddressParameter, remarksParameter, @return);
        }
    
        public virtual int UPdateLocation(string addressline1, string addressline2, string addressline3, string addressline4, string licencenumber, string serverprinterip, string localprinterip)
        {
            var addressline1Parameter = addressline1 != null ?
                new ObjectParameter("addressline1", addressline1) :
                new ObjectParameter("addressline1", typeof(string));
    
            var addressline2Parameter = addressline2 != null ?
                new ObjectParameter("addressline2", addressline2) :
                new ObjectParameter("addressline2", typeof(string));
    
            var addressline3Parameter = addressline3 != null ?
                new ObjectParameter("addressline3", addressline3) :
                new ObjectParameter("addressline3", typeof(string));
    
            var addressline4Parameter = addressline4 != null ?
                new ObjectParameter("addressline4", addressline4) :
                new ObjectParameter("addressline4", typeof(string));
    
            var licencenumberParameter = licencenumber != null ?
                new ObjectParameter("licencenumber", licencenumber) :
                new ObjectParameter("licencenumber", typeof(string));
    
            var serverprinteripParameter = serverprinterip != null ?
                new ObjectParameter("serverprinterip", serverprinterip) :
                new ObjectParameter("serverprinterip", typeof(string));
    
            var localprinteripParameter = localprinterip != null ?
                new ObjectParameter("localprinterip", localprinterip) :
                new ObjectParameter("localprinterip", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPdateLocation", addressline1Parameter, addressline2Parameter, addressline3Parameter, addressline4Parameter, licencenumberParameter, serverprinteripParameter, localprinteripParameter);
        }
    
        public virtual int Updatelocationnew(Nullable<int> code, string addressline1, string addressline2, string addressline3, string licencenumber, string serverprinterip, string localprinterip, string updatedBy, string remarks)
        {
            var codeParameter = code.HasValue ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(int));
    
            var addressline1Parameter = addressline1 != null ?
                new ObjectParameter("addressline1", addressline1) :
                new ObjectParameter("addressline1", typeof(string));
    
            var addressline2Parameter = addressline2 != null ?
                new ObjectParameter("addressline2", addressline2) :
                new ObjectParameter("addressline2", typeof(string));
    
            var addressline3Parameter = addressline3 != null ?
                new ObjectParameter("addressline3", addressline3) :
                new ObjectParameter("addressline3", typeof(string));
    
            var licencenumberParameter = licencenumber != null ?
                new ObjectParameter("licencenumber", licencenumber) :
                new ObjectParameter("licencenumber", typeof(string));
    
            var serverprinteripParameter = serverprinterip != null ?
                new ObjectParameter("serverprinterip", serverprinterip) :
                new ObjectParameter("serverprinterip", typeof(string));
    
            var localprinteripParameter = localprinterip != null ?
                new ObjectParameter("localprinterip", localprinterip) :
                new ObjectParameter("localprinterip", typeof(string));
    
            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(string));
    
            var remarksParameter = remarks != null ?
                new ObjectParameter("remarks", remarks) :
                new ObjectParameter("remarks", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Updatelocationnew", codeParameter, addressline1Parameter, addressline2Parameter, addressline3Parameter, licencenumberParameter, serverprinteripParameter, localprinteripParameter, updatedByParameter, remarksParameter);
        }
    }
}
